### ISSUE TITLE
For-In Order

### ISSUE THREAD

**Issue by jorydotcom** [tc39/js-outreach-groups#23]
https://github.com/tc39/proposal-for-in-order

(sharon / ujjwal)

**Comment by hemanth** [comment]
@ryzokuken Is it ok if I can take over this issue?

**Comment by littledan** [comment]
Hmm, I don't think this proposal would be very interesting or meaningful for JS programmers.

**Comment by hemanth** [comment]
Nods, for most of them it should not matter, maybe we should close this for now or put it in the back burner?
