### ISSUE TITLE
New to stage-3 and stage-4

### ISSUE THREAD

**Issue by hemanth** [tc39/js-outreach-groups#38]
Below are the new ones which we can write about:

- Intl.DisplayNames Stage 4
- .item() for indexables Stage 3
- Import Assertions Stage 3

**Comment by hemanth** [comment]
[`item()`](https://dev.to/hemanth/item-on-built-in-indexables-51a4) is covered.

**Comment by MayaLekova** [comment]
> [`item()`](https://dev.to/hemanth/item-on-built-in-indexables-51a4) is covered.

Forgot to mention this, but I've read it and it looks good to me, thanks for writing it!
