### ISSUE TITLE
Calendar Invite Request

### ISSUE THREAD

**Issue by snitin315** [tc39/js-outreach-groups#46]
Hi,

I would like to get a calendar invite for the meetings.

It will be helpful for my learning and keep me up-to-date on the emerging standards of Javascript.

Thanks.

**Comment by romulocintra** [comment]
Thank you @snitin315 will send an invite shortly, FYI I edited your details to hide your email address

**Comment by snitin315** [comment]
@romulocintra Thank you.

**Comment by snitin315** [comment]
@romulocintra Thanks, I got invited to the `Educators` meeting. Can I get invited to `Tools and transpilers` meetings as well?

**Comment by romulocintra** [comment]
Sure , please just feel in [form](https://docs.google.com/forms/d/e/1FAIpQLSfnYeL6UMPe4ZKcfEP8slKubyv1KYlKE8efaLJznMlx1qt9kw/viewform) cause we don't keep register from the previous requests. thank you @snitin315

**Comment by snitin315** [comment]
Thank you.
